/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    DefaultLayout: typeof import('./components/gallerys/DefaultLayout/index.vue')['default']
    Edit: typeof import('./components/gallerys/WebglPrinter/edit.vue')['default']
    GalleryArea: typeof import('./components/layouts/GalleryArea.vue')['default']
    GalleryTab: typeof import('./components/layouts/GalleryTab.vue')['default']
    Header: typeof import('./components/layouts/Header.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideMenu: typeof import('./components/layouts/SideMenu.vue')['default']
    SortAlgorithm: typeof import('./components/gallerys/SortAlgorithm/index.vue')['default']
    WebglPrinter: typeof import('./components/gallerys/WebglPrinter/index.vue')['default']
  }
}
